trigger:
- master

pool:
  name: Default

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ado-acr-sc'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'ado-aks-kubeconfig'
    azureResourceGroup: 'private-devops'
    kubernetesCluster: 'devopsprivate-aks-cluster'
    command: 'apply'
    arguments: '-f deploy.yaml'