trigger:
- master

pool:
  name: Default

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ado-acr-sc'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Microsoft Azure Internal Consumption(6af4982f-1b04-49ae-8cca-7856f3783a19)'
    azureResourceGroup: 'private-devops'
    kubernetesCluster: 'devopsprivate-aks-cluster'
    namespace: 'nginx'
    command: 'apply'
    arguments: '-f deploy.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Container Registry'
    dockerRegistryEndpoint: 'ado-acr-sc'
    forceUpdate: false
